from datetime import datetime

def parse_universal_arguments(**kwargs) -> str: ...
def clean_dataset_name(name: str) -> str: ...
def clean_shell_input(string: str) -> str: ...
def escape_block_string(original_string: str) -> str: ...
def parse_datetime(date_string: str, time_string: str) -> datetime: ...
def parse_unknown(attribute: str | None) -> str | int | None: ...
def cast_int_optional(attribute: str | int | None) -> int | None: ...
def zoau_json_load(json_text: str) -> tuple[dict, dict]: ...
